services:
  server:
    build:
      context: .
    env_file: .env.docker
    environment:
      NODE_ENV: production
    ports:
      - "5678:5678"
    volumes:
      - .:/usr/src/app
    networks:
      - backend-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: bitnami/postgresql:latest
    env_file: .env.docker
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - ./postgres_data:/bitnami/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env.docker
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - backend-network

  redis:
    image: redis:7.4-rc2-alpine
    ports:
      - "9999:9999"
    networks:
      - backend-network

volumes:
  postgres_data:
    driver: local

networks:
  backend-network:
    driver: bridge
