version: '3'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5678:5678
    volumes:
      - .:/usr/src/app

  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: DOCKER
      POSTGRES_PASSWORD: DOCKER
      POSTGRES_DB: polls
   
    ports:
      - "5432:5432" 
    networks:
      - backend-network  # Ensure this network exists 
    volumes:
      - postgres_data:/bitnami/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: admin          # Replace with your desired password
    ports:
      - "80:80"
    depends_on:
      - postgres   # Ensure pgAdmin starts after PostgreSQL
    networks:
      - backend-network

volumes:
  postgres_data:
    driver: local

networks:
  backend-network:
    driver: bridge
